name: Build SunamoXliffParser

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoXliffParser
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoXliffParser/SunamoXliffParser.csproj

    - name: Build
      run: dotnet build SunamoXliffParser/SunamoXliffParser.csproj --configuration Release --no-restore

  test:
    name: Test SunamoXliffParser.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoXliffParser.Tests/SunamoXliffParser.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoXliffParser.Tests/SunamoXliffParser.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoXliffParser.Tests/SunamoXliffParser.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
